// Code generated by protoc-gen-go. DO NOT EDIT.
// source: text.proto

package main

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Test struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Stature              int32    `protobuf:"varint,2,opt,name=stature,proto3" json:"stature,omitempty"`
	Weight               []int64  `protobuf:"varint,3,rep,packed,name=weight,proto3" json:"weight,omitempty"`
	Motto                string   `protobuf:"bytes,4,opt,name=motto,proto3" json:"motto,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Test) Reset()         { *m = Test{} }
func (m *Test) String() string { return proto.CompactTextString(m) }
func (*Test) ProtoMessage()    {}
func (*Test) Descriptor() ([]byte, []int) {
	return fileDescriptor_a8e73d1ce47f9297, []int{0}
}

func (m *Test) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Test.Unmarshal(m, b)
}
func (m *Test) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Test.Marshal(b, m, deterministic)
}
func (m *Test) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Test.Merge(m, src)
}
func (m *Test) XXX_Size() int {
	return xxx_messageInfo_Test.Size(m)
}
func (m *Test) XXX_DiscardUnknown() {
	xxx_messageInfo_Test.DiscardUnknown(m)
}

var xxx_messageInfo_Test proto.InternalMessageInfo

func (m *Test) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Test) GetStature() int32 {
	if m != nil {
		return m.Stature
	}
	return 0
}

func (m *Test) GetWeight() []int64 {
	if m != nil {
		return m.Weight
	}
	return nil
}

func (m *Test) GetMotto() string {
	if m != nil {
		return m.Motto
	}
	return ""
}

func init() {
	proto.RegisterType((*Test)(nil), "myproto.Test")
}

func init() { proto.RegisterFile("text.proto", fileDescriptor_a8e73d1ce47f9297) }

var fileDescriptor_a8e73d1ce47f9297 = []byte{
	// 125 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x2a, 0x49, 0xad, 0x28,
	0xd1, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0xcf, 0xad, 0x04, 0x33, 0x94, 0x92, 0xb8, 0x58,
	0x42, 0x52, 0x8b, 0x4b, 0x84, 0x84, 0xb8, 0x58, 0xf2, 0x12, 0x73, 0x53, 0x25, 0x18, 0x15, 0x18,
	0x35, 0x38, 0x83, 0xc0, 0x6c, 0x21, 0x09, 0x2e, 0xf6, 0xe2, 0x92, 0xc4, 0x92, 0xd2, 0xa2, 0x54,
	0x09, 0x26, 0x05, 0x46, 0x0d, 0xd6, 0x20, 0x18, 0x57, 0x48, 0x8c, 0x8b, 0xad, 0x3c, 0x35, 0x33,
	0x3d, 0xa3, 0x44, 0x82, 0x59, 0x81, 0x59, 0x83, 0x39, 0x08, 0xca, 0x13, 0x12, 0xe1, 0x62, 0xcd,
	0xcd, 0x2f, 0x29, 0xc9, 0x97, 0x60, 0x01, 0x1b, 0x03, 0xe1, 0x24, 0xb1, 0x81, 0xad, 0x32, 0x06,
	0x04, 0x00, 0x00, 0xff, 0xff, 0xf4, 0x98, 0x41, 0x6d, 0x81, 0x00, 0x00, 0x00,
}
